name: build_value_navigation_saver
version: 0.3.3
description: >-
  This library is a helper library for converting routes with arguments to a string.
repository: https://github.com/scalio/flutter_navigation_saver
homepage: https://github.com/scalio/flutter_navigation_saver/tree/master/built_value_navigation_saver
documentation: https://github.com/scalio/flutter_navigation_saver/tree/master/built_value_navigation_saver
issue_tracker: https://github.com/scalio/flutter_navigation_saver/issues

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^7.0.0
  built_collection: ^4.0.0
  navigation_saver: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  build_runner: ^1.0.0
  built_value_generator: ^7.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
